baseurl = "https://mtlynch.io"
title = "mtlynch.io"
languagecode = "en"
defaultcontentlanguage = "en"

timeout = 300000

# We don't want to canonify URLs because it prevents us from
# deploying drafts of the site to alternate hosts.
canonifyurls = false

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

buildFuture = true

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    style = "native"
  [markup.goldmark.renderer]
    # Allow Markdown to include embedded HTML.
    unsafe= true

[permalinks]
    posts = "/:filename/"

[social]
twitter = "deliberatecoder"

[params]
    dateFormat = "January 2, 2006"
    author = "Michael Lynch"
    info = "By day, a simple software engineer. By night, also a software engineer."
    description = "Updates about my life and what I learn about creating software"
    currentproject = "Paternity Leave"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon/favicon-32x32.png"
    favicon_16 = "/images/favicon/favicon-16x16.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    photoWidths = [300, 600, 800, 1200]

    talkyardServerUrl = "https://comments.mtlynch.io"
    talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

[imaging]
quality = 90
resampleFilter = "Lanczos"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/mtlynch/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/deliberatecoder/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Retrospectives"
    weight = 2
    url = "/retrospectives/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Book Reports"
    weight = 4
    url = "/book-reports/"
[[menu.main]]
    name = "About"
    weight = 5
    url = "/about/"
